<a href="https://colab.research.google.com/github/sethkipsangmutuba/Data-Visualization/blob/main/Session_B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Manipulation with Pandas
##Seth Kipsang

### Installing and Using Pandas

### Introducing Pandas Objects

### The Pandas Series Object

### The Pandas DataFrame Object

### The Pandas Index Object

### Data Indexing and Selection

### Data Selection in Series

### Data Selection in DataFrame

### Operating on Data in Pandas

### Ufuncs: Index Preservation

### UFuncs: Index Alignment

### Ufuncs: Operations Between DataFrame and Series

### Handling Missing Data

### Trade-Offs in Missing Data Conventions

### Missing Data in Pandas

### Operating on Null Values

In [195]:
import warnings; warnings.filterwarnings("ignore", category=FutureWarning)

## Data Manipulation with Pandas

Pandas builds on NumPy to provide more flexible data structures, especially the DataFrame, which supports labeled rows and columns, heterogeneous data types, and missing values.

While NumPy arrays are efficient for structured numerical data, they lack features like labels and tools for handling incomplete or irregular data.

Pandas addresses these limitations by offering powerful data manipulation capabilities similar to those in databases and spreadsheets.

Its core structures, Series and DataFrame, are designed for tasks such as grouping, reshaping, and handling real-world messy data.

The focus is on effectively using these structures for practical data manipulation tasks.

##1.1 Installing and Using Pandas

Pandas requires NumPy and, when built from source, appropriate tools for compiling its underlying C and Cython components. It is typically included in distributions like Anaconda.

After installation, it can be imported and its version checked.

By convention, Pandas is imported using the alias `pd`.

Interactive environments provide tools like tab-completion to explore available functions and the `?` operator to access documentation.

More detailed guidance is available in the official Pandas documentation: http://pandas.pydata.org/

In [196]:
#IMPORT PANDAS (conventional alias)

import pandas as pd
import numpy as np

#CHECK VERSION

print("Pandas version:", pd.__version__)

# NOTE (no execution needed for installation)

## Pandas depends on NumPy.
## When built from source, it may require C/Cython compilation tools.
## It is commonly included in distributions like Anaconda.


# INTERACTIVE USAGE NOTES (for Jupyter / IPython)

# Tab completion example:
# pd.<TAB>

# Documentation inspection:
# pd.DataFrame?
# pd.Series?
# pd.read_csv?

# OFFICIAL DOCUMENTATION REFERENCE

print("Official Pandas documentation:")
print("http://pandas.pydata.org/")

Pandas version: 2.2.2
Official Pandas documentation:
http://pandas.pydata.org/

##1.2 Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices. Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are. Thus, before going further, let’s introduce three fundamental Pandas data structures: the Series, DataFrame, and Index.

We will start with the standard NumPy and Pandas imports.

---

##1.2.1 The Pandas Series Object

A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array.

As seen, the Series wraps both a sequence of values and a sequence of indices, which can be accessed with the `values` and `index` attributes. The values are simply a familiar NumPy array.

The index is an array-like object of type `pd.Index`.

Like with a NumPy array, data can be accessed by the associated index via Python square-bracket notation.

The Pandas Series is more general and flexible than the one-dimensional NumPy array that it emulates.

---

### Series as generalized NumPy array

The key difference is the presence of the index: while the NumPy array has an implicitly defined integer index, the Pandas Series has an explicitly defined index associated with the values.

This explicit index definition gives the Series object additional capabilities. The index need not be an integer, but can consist of values of any desired type, such as strings.

Item access works as expected, and indices can also be noncontiguous or nonsequential.

---

### Series as specialized dictionary

A Pandas Series can be viewed as a specialization of a Python dictionary. A dictionary maps arbitrary keys to values, while a Series maps typed keys to typed values. This typing makes it more efficient than Python dictionaries for certain operations.

This analogy becomes clearer by constructing a Series directly from a dictionary. By default, the index is drawn from the sorted keys, and dictionary-style item access can be performed.

Unlike a dictionary, the Series also supports array-style operations such as slicing.

---

###Constructing Series objects

A Pandas Series can be constructed as:

`pd.Series(data, index=index)`

where `index` is optional, and `data` can take various forms.

Data can be a list or NumPy array, in which case the index defaults to an integer sequence.

Data can be a scalar, which is repeated to fill the specified index.

Data can be a dictionary, in which case the index defaults to the sorted dictionary keys.

In each case, the index can be explicitly set if a different result is preferred.

In such cases, the Series is populated only with the explicitly identified keys.

LOAD IRIS DATASET

In [197]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df['target'] = iris.target

CREATE SERIES FROM IRIS COLUMNS (1D DATA)

In [198]:
sepal_length = pd.Series(df.iloc[:, 0].values)
sepal_width  = pd.Series(df.iloc[:, 1].values)

print("Series from Iris (sepal length):\n", sepal_length.head())

Series from Iris (sepal length):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
dtype: float64

SERIES WITH EXPLICIT INDEX (LABELLED OBSERVATIONS)

In [199]:
s1 = pd.Series(df.iloc[:10, 0].values,
               index=[f"obs_{i}" for i in range(10)])

print("\nSeries with custom index:\n", s1)

# Access by label
print("\nAccess obs_3:", s1["obs_3"])

Series with custom index:
 obs_0    5.1
obs_1    4.9
obs_2    4.7
obs_3    4.6
obs_4    5.0
obs_5    5.4
obs_6    4.6
obs_7    5.0
obs_8    4.4
obs_9    4.9
dtype: float64

Access obs_3: 4.6

SERIES AS DICTIONARY (FEATURE SUMMARY)

In [200]:
feature_means = {
    "sepal_length": df["sepal length (cm)"].mean(),
    "sepal_width": df["sepal width (cm)"].mean(),
    "petal_length": df["petal length (cm)"].mean(),
    "petal_width": df["petal width (cm)"].mean()
}

s2 = pd.Series(feature_means)
s2

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

 SERIES WITH EXPLICIT INDEX FILTERING

In [201]:
s3 = pd.Series(feature_means,
               index=["sepal_length", "petal_width", "missing_feature"])

print("\nSeries with reindexed keys:\n", s3)

Series with reindexed keys:
 sepal_length       5.843333
petal_width        1.199333
missing_feature         NaN
dtype: float64

SCALAR BROADCASTING USING IRIS SIZE

In [202]:
s4 = pd.Series(1.0, index=df.index[:5])

print("\nScalar broadcast Series:\n", s4)

Scalar broadcast Series:
 0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

ARRAY-LIKE SLICING BEHAVIOR

In [203]:
print("\nSlice of sepal_length Series:\n", sepal_length[:5].values)

Slice of sepal_length Series:
 [5.1 4.9 4.7 4.6 5. ]

CORE INTERPRETATION

In [204]:
print("\nKey Insight:")
print("- Series = 1D labeled array over Iris features")
print("- Combines NumPy array efficiency with explicit indexing")
print("- Supports dictionary-like and array-like behavior simultaneously")

Key Insight:
- Series = 1D labeled array over Iris features
- Combines NumPy array efficiency with explicit indexing
- Supports dictionary-like and array-like behavior simultaneously

##1.2.2 The Pandas DataFrame Object

The next fundamental structure in Pandas is the DataFrame. Like the Series object, the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.

---

### DataFrame as a generalized NumPy array

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. Just as a two-dimensional array can be seen as an ordered sequence of aligned one-dimensional columns, a DataFrame can be viewed as a sequence of aligned Series objects that share the same index.

To demonstrate this, we construct a Series listing the area of each state and combine it with the population Series to form a two-dimensional object using a dictionary.

Like the Series object, the DataFrame has an `index` attribute that provides access to row labels. It also has a `columns` attribute, which is an Index object holding the column labels.

Thus, the DataFrame generalizes a two-dimensional NumPy array by allowing both rows and columns to have labeled indices.

---

### DataFrame as specialized dictionary

A DataFrame can also be viewed as a specialization of a dictionary. Instead of mapping a key to a single value, it maps a column name to a Series of column data. Accessing a column returns the corresponding Series.

This leads to an important distinction: in a NumPy array, accessing data by index typically returns rows, whereas in a DataFrame, accessing by a column name returns columns. For this reason, it is often more intuitive to think of DataFrames as generalized dictionaries.

---

### Constructing DataFrame objects

A Pandas DataFrame can be constructed in several ways:

- From a single Series object, resulting in a one-column DataFrame  
- From a list of dictionaries, where each dictionary represents a row; missing keys are filled with NaN values  
- From a dictionary of Series objects, aligning data by index  
- From a two-dimensional NumPy array, with optional specification of column and row labels  
- From a NumPy structured array, where fields map naturally to DataFrame columns

LOAD IRIS DATASET

In [205]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target

DATAFRAME AS GENERALIZED NUMPY ARRAY

In [206]:
print("Shape (rows, columns):", df.shape)

print("\nColumn labels:\n", df.columns)

print("\nRow index:\n", df.index)

# Each column behaves like a Series (aligned vector)
sepal_length_series = df["sepal length (cm)"]

print("\nSingle column as Series:\n", sepal_length_series.head())

Shape (rows, columns): (150, 5)

Column labels:
 Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

Row index:
 RangeIndex(start=0, stop=150, step=1)

Single column as Series:
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

DATAFRAME AS DICTIONARY OF SERIES

In [207]:
print("\nAccess column via dict-like syntax:\n", df["petal width (cm)"].head())

# Each column is a Series object
print("\nType of column:", type(df["petal width (cm)"]))

Access column via dict-like syntax:
 0    0.2
1    0.2
2    0.2
3    0.2
4    0.2
Name: petal width (cm), dtype: float64

Type of column: <class 'pandas.core.series.Series'>

CONSTRUCTION METHOD 1: FROM SERIES

In [208]:
s = pd.Series(df["sepal length (cm)"])

df_from_series = pd.DataFrame(s, columns=["sepal_length"])

print("\nDataFrame from Series:\n", df_from_series.head())

DataFrame from Series:
 Empty DataFrame
Columns: [sepal_length]
Index: []

CONSTRUCTION METHOD 2: LIST OF DICTIONARIES (ROWS)

In [209]:
row_dicts = [
    {"sepal_length": df.iloc[0, 0], "petal_length": df.iloc[0, 2]},
    {"sepal_length": df.iloc[1, 0]},  # missing key → NaN
    {"sepal_length": df.iloc[2, 0], "petal_length": df.iloc[2, 2]},
]

df_from_rows = pd.DataFrame(row_dicts)

print("\nDataFrame from list of dicts:\n", df_from_rows)

DataFrame from list of dicts:
    sepal_length  petal_length
0           5.1           1.4
1           4.9           NaN
2           4.7           1.3

 CONSTRUCTION METHOD 3: DICT OF SERIES

In [210]:
df_from_dict_series = pd.DataFrame({
    "sepal_length": df["sepal length (cm)"],
    "petal_length": df["petal length (cm)"]
})

print("\nDataFrame from dict of Series:\n", df_from_dict_series.head())

DataFrame from dict of Series:
    sepal_length  petal_length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

 CONSTRUCTION METHOD 4: NUMPY ARRAY

In [211]:
array = df.iloc[:, :4].to_numpy()

df_from_array = pd.DataFrame(
    array,
    columns=["sepal_length", "sepal_width", "petal_length", "petal_width"]
)

print("\nDataFrame from NumPy array:\n", df_from_array.head())

DataFrame from NumPy array:
    sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

COLUMN VS ROW ACCESS DIFFERENCE

In [212]:
print("\nColumn access (returns Series):\n", df["sepal length (cm)"].head())

print("\nRow access using iloc:\n", df.iloc[0])

Column access (returns Series):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

Row access using iloc:
 sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
target               0.0
Name: 0, dtype: float64

CORE INSIGHT

In [213]:
print("\nKey Insight:")
print("- DataFrame = collection of aligned Series (column-wise structure)")
print("- Acts like a dictionary of labeled columns")
print("- Rows and columns both have explicit indices")

Key Insight:
- DataFrame = collection of aligned Series (column-wise structure)
- Acts like a dictionary of labeled columns
- Rows and columns both have explicit indices

##1.2.3 The Pandas Index Object

Both the Series and DataFrame objects contain an explicit index that lets you reference and modify data. This Index object can be thought of either as an immutable array or as an ordered set (technically a multiset, since it may contain repeated values). These views influence the operations available on Index objects.

---

###Index as immutable array

The Index object behaves in many ways like an array. Standard Python indexing can be used to retrieve values or slices.

Index objects also expose familiar attributes such as size, shape, dimensionality, and data type.

A key difference from NumPy arrays is immutability: Index objects cannot be modified through assignment. This property makes them safer to share across multiple DataFrames and arrays without unintended side effects.

---

###Index as ordered set

Pandas objects support operations such as joins that rely on set-like behavior. The Index object follows conventions similar to Python’s set structure, enabling operations like unions, intersections, and differences.

These set operations can also be accessed through object methods such as `intersection`, providing flexible ways to combine and compare indices.

LOAD IRIS DATASET AND BUILD DATAFRAME

In [214]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target
df["target"]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

EXTRACT INDEX OBJECTS

In [215]:
row_index = df.index
col_index = df.columns

print("Row Index (first 10):\n", row_index[:10])
print("\nColumn Index:\n", col_index)

Row Index (first 10):
 RangeIndex(start=0, stop=10, step=1)

Column Index:
 Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

INDEX AS IMMUTABLE ARRAY

In [216]:
# Array-like access
print("\nFirst 5 row labels:\n", row_index[:5])
print("\nFirst 3 column labels:\n", col_index[:3])

First 5 row labels:
 RangeIndex(start=0, stop=5, step=1)

First 3 column labels:
 Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)'], dtype='object')

In [217]:
# Attributes
print("\nIndex size:", row_index.size)
print("Index shape:", row_index.shape)
print("Index ndim:", row_index.ndim)
print("Index dtype:", row_index.dtype)

Index size: 150
Index shape: (150,)
Index ndim: 1
Index dtype: int64

IMMUTABILITY DEMONSTRATION (no assignment allowed)

In [218]:
try:
    row_index[0] = 999  # should fail
except TypeError as e:
    print("\nImmutability test (expected error):")
    print(e)

Immutability test (expected error):
Index does not support mutable operations

INDEX AS ORDERED SET

In [219]:
index_a = pd.Index(["a", "b", "c", "d"])
index_b = pd.Index(["c", "d", "e", "f"])

In [220]:
# Union
union_index = index_a.union(index_b)
print("\nUnion:\n", union_index)

Union:
 Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [221]:
# Intersection
intersection_index = index_a.intersection(index_b)
print("\nIntersection:\n", intersection_index)

Intersection:
 Index(['c', 'd'], dtype='object')

In [222]:
# Difference
difference_index = index_a.difference(index_b)
print("\nDifference (A - B):\n", difference_index)

Difference (A - B):
 Index(['a', 'b'], dtype='object')

INDEX ALIGNMENT IDEA (DATAFRAME CONTEXT)

In [223]:
df1 = df.iloc[:5, :2]
df2 = df.iloc[2:7, :2]

aligned_sum = df1 + df2  # automatic index alignment (NaN introduced)

print("\nIndex-aligned addition (NaN where misaligned):\n", aligned_sum)

Index-aligned addition (NaN where misaligned):
    sepal length (cm)  sepal width (cm)
0                NaN               NaN
1                NaN               NaN
2                9.4               6.4
3                9.2               6.2
4               10.0               7.2
5                NaN               NaN
6                NaN               NaN

CORE INSIGHT

In [224]:
print("\nKey Insight:")
print("- Index is immutable (safe shared metadata)")
print("- Behaves like ordered set for alignment operations")
print("- Enables automatic alignment in arithmetic between DataFrames")

Key Insight:
- Index is immutable (safe shared metadata)
- Behaves like ordered set for alignment operations
- Enables automatic alignment in arithmetic between DataFrames

##1.3 Data Indexing and Selection

Previously, methods for accessing and modifying values in NumPy arrays were introduced, including direct indexing, slicing, masking, fancy indexing, and combinations of these approaches.

Similar mechanisms exist for Pandas Series and DataFrame objects. If you are familiar with NumPy-style indexing, the corresponding Pandas operations will feel familiar, though there are important differences to keep in mind.

We begin with the one-dimensional Series structure, then extend the discussion to the two-dimensional DataFrame structure.

##1.3.1 Data Selection in Series

A Series object behaves both like a one-dimensional NumPy array and like a Python dictionary. These two mental models help explain how indexing and selection work in practice.

---

### Series as dictionary

A Series provides a mapping between keys (index labels) and values.

It supports dictionary-like access to values using keys. It also allows inspection of keys and values using familiar dictionary-style methods.

A Series can be modified dynamically by assigning values to new keys, similar to extending a dictionary. This mutability is managed internally by Pandas.

---

### Series as one-dimensional array

A Series also supports array-like operations such as slicing, masking, and fancy indexing, similar to NumPy arrays.

Slicing behavior depends on whether explicit or implicit indexing is used. When slicing with labels, the final element is included, while integer-based slicing follows standard Python conventions where the endpoint is excluded.

---

### Indexers: loc, iloc, and ix

To reduce ambiguity, Pandas provides explicit indexing operators.

- `loc` selects data using explicit index labels.  
- `iloc` selects data using integer-based positional indexing.  
- `ix` was introduced as a hybrid of both approaches, but is now largely deprecated in favor of clearer use of `loc` and `iloc`.

Using explicit indexers improves readability and reduces errors, especially when working with integer-indexed Series.

 CREATE SERIES FROM IRIS DATA

In [225]:
s = pd.Series(
    df["sepal length (cm)"].values,
    index=[f"obs_{i}" for i in range(len(df))]
)

print("Series preview:\n", s.head())

Series preview:
 obs_0    5.1
obs_1    4.9
obs_2    4.7
obs_3    4.6
obs_4    5.0
dtype: float64

SERIES AS DICTIONARY

In [226]:
# Key-based access (dictionary-like)
print("\nAccess obs_3:", s["obs_3"])

Access obs_3: 4.6

In [227]:
# Adding new key-value pair (dynamic extension)
s["new_obs"] = 10.5
print("\nAfter adding new key:\n", s.tail())

After adding new key:
 obs_146     6.3
obs_147     6.5
obs_148     6.2
obs_149     5.9
new_obs    10.5
dtype: float64

In [228]:
# Inspect keys and values
print("\nKeys (index):\n", s.index[:5])
print("\nValues:\n", s.values[:5])

Keys (index):
 Index(['obs_0', 'obs_1', 'obs_2', 'obs_3', 'obs_4'], dtype='object')

Values:
 [5.1 4.9 4.7 4.6 5. ]

SERIES AS 1D ARRAY

In [229]:
# Slicing (positional-like behavior via implicit order)
print("\nSlice obs_0 to obs_4:\n", s[:5])

Slice obs_0 to obs_4:
 obs_0    5.1
obs_1    4.9
obs_2    4.7
obs_3    4.6
obs_4    5.0
dtype: float64

In [230]:
# Boolean masking (vectorized filtering)
mask = s.values > 5.5
print("\nMasked values (>5.5):\n", s[mask][:5])

Masked values (>5.5):
 obs_14    5.8
obs_15    5.7
obs_18    5.7
obs_50    7.0
obs_51    6.4
dtype: float64

In [231]:
# Fancy indexing
print("\nFancy indexing:\n", s[["obs_1", "obs_3", "obs_5"]])

Fancy indexing:
 obs_1    4.9
obs_3    4.6
obs_5    5.4
dtype: float64

loc vs iloc

In [232]:
# loc → label-based
print("\nloc['obs_2']:", s.loc["obs_2"])

loc['obs_2']: 4.7

In [233]:
# iloc → position-based
print("iloc[2]:", s.iloc[2])

iloc[2]: 4.7

In [234]:
# Slice comparison
print("\nloc slice (inclusive):")
print(s.loc["obs_2":"obs_5"])

loc slice (inclusive):
obs_2    4.7
obs_3    4.6
obs_4    5.0
obs_5    5.4
dtype: float64

In [235]:
print("\niloc slice (exclusive stop):")
print(s.iloc[2:5])

iloc slice (exclusive stop):
obs_2    4.7
obs_3    4.6
obs_4    5.0
dtype: float64

##Insight

- Series behaves like BOTH dictionary (label access) and array (positional access)
- `loc` uses labels (inclusive slicing)
- `iloc` uses integer positions (Python-style slicing)
- Clear indexing avoids ambiguity and logical errors

##1.3.2 Data Selection in DataFrame

A DataFrame can be viewed either as a two-dimensional structured array or as a dictionary of aligned Series sharing the same index.

---

## DataFrame as a dictionary

A DataFrame is often interpreted as a collection of Series objects (columns). Each column can be accessed using dictionary-style indexing or attribute-style access when the column name is valid.

Column access returns the corresponding Series, and arithmetic between Series allows creation of new columns, such as computing derived values like density from population and area.

Attribute-style access is a convenient shortcut but is not always safe, especially when column names conflict with built-in methods or are not valid identifiers.

---

## DataFrame as a two-dimensional array

A DataFrame can also be viewed as a matrix-like structure. The underlying data can be accessed as a NumPy array, and it supports operations like transposition.

However, unlike a pure NumPy array, direct indexing behaves differently: single indexing typically refers to columns rather than rows, due to label-based structure.

To handle both row and column selection consistently, Pandas provides explicit indexers:

- `iloc`: position-based (integer indexing like NumPy)  
- `loc`: label-based (index and column names)  
- `ix`: hybrid approach (older and discouraged due to ambiguity)  

These indexers support slicing, masking, and combined row/column selection.

---

## Selection and modification

DataFrames support boolean filtering and mixed indexing, allowing conditions to select specific rows and columns. Values can also be updated directly using `loc` or `iloc`.

---

## Additional conventions

- Column selection uses indexing syntax  
- Row slicing uses standard slice notation  
- Boolean masks are applied row-wise  

These conventions make DataFrame operations flexible but require careful attention to avoid confusion between row and column selection.

LOAD IRIS DATASET INTO DATAFRAME

In [236]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target

DATAFRAME AS DICTIONARY OF SERIES

In [237]:
# Column access (dictionary-style)
sepal_length = df["sepal length (cm)"]
petal_length = df["petal length (cm)"]

print("Column (Series) preview:\n", sepal_length.head())

Column (Series) preview:
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

In [238]:
# Attribute-style access (only works if valid identifier)
df_simple = df.copy()
df_simple.columns = ["sl", "sw", "pl", "pw", "target"]

print("\nAttribute-style access (df_simple.sl):\n", df_simple.sl.head())

Attribute-style access (df_simple.sl):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sl, dtype: float64

DERIVED COLUMN CREATION (Series arithmetic)

In [239]:
df["petal_ratio"] = df["petal length (cm)"] / df["petal width (cm)"]

print("\nDerived feature (petal_ratio):\n", df["petal_ratio"].head())

Derived feature (petal_ratio):
 0    7.0
1    7.0
2    6.5
3    7.5
4    7.0
Name: petal_ratio, dtype: float64

DATAFRAME AS 2D ARRAY

In [240]:
print("\nUnderlying NumPy array:\n", df.iloc[:, :4].to_numpy()[:3])

# Transpose (matrix-like operation)
print("\nTransposed view (first 5 cols x rows):\n", df.iloc[:, :4].T.iloc[:, :3])

Underlying NumPy array:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

Transposed view (first 5 cols x rows):
                      0    1    2
sepal length (cm)  5.1  4.9  4.7
sepal width (cm)   3.5  3.0  3.2
petal length (cm)  1.4  1.4  1.3
petal width (cm)   0.2  0.2  0.2

COLUMN VS ROW ACCESS BEHAVIOR

In [241]:
print("\nSingle bracket access (column):\n", df["sepal length (cm)"].head())

print("\nRow access using iloc:\n", df.iloc[0])

Single bracket access (column):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64

Row access using iloc:
 sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
target               0.0
petal_ratio          7.0
Name: 0, dtype: float64

EXPLICIT INDEXERS: loc vs iloc

In [242]:
# loc → label-based (here index labels are integers but still explicit)
print("\nloc row selection (0 to 3):\n", df.loc[0:3, ["sepal length (cm)", "target"]])

# iloc → positional indexing (NumPy-like)
print("\niloc row selection (0 to 3):\n", df.iloc[0:3, 0:2])

loc row selection (0 to 3):
    sepal length (cm)  target
0                5.1       0
1                4.9       0
2                4.7       0
3                4.6       0

iloc row selection (0 to 3):
    sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2

BOOLEAN FILTERING (row-wise mask)

In [243]:
mask = df["sepal length (cm)"] > 6.0

filtered = df[mask]
filtered

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,petal_ratio
50,7.0,3.2,4.7,1.4,1,3.357143
51,6.4,3.2,4.5,1.5,1,3.000000
52,6.9,3.1,4.9,1.5,1,3.266667
54,6.5,2.8,4.6,1.5,1,3.066667
56,6.3,3.3,4.7,1.6,1,2.937500
...,...,...,...,...,...,...
144,6.7,3.3,5.7,2.5,2,2.280000
145,6.7,3.0,5.2,2.3,2,2.260870
146,6.3,2.5,5.0,1.9,2,2.631579
147,6.5,3.0,5.2,2.0,2,2.600000
148,6.2,3.4,5.4,2.3,2,2.347826

MIXED ROW-COLUMN SELECTION

In [244]:
print("\nloc mixed selection:\n",
      df.loc[mask, ["sepal length (cm)", "petal length (cm)"]].head())

print("\niloc mixed selection:\n",
      df.iloc[0:5, [0, 2]])

loc mixed selection:
     sepal length (cm)  petal length (cm)
50                7.0                4.7
51                6.4                4.5
52                6.9                4.9
54                6.5                4.6
56                6.3                4.7

iloc mixed selection:
    sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5
4                5.0                1.4

DIRECT MODIFICATION USING loc

In [245]:
df.loc[0:2, "target"] = -1  # safe in-place update

print("\nModified target values (first rows):\n", df.head(5))

Modified target values (first rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

   target  petal_ratio
0      -1          7.0
1      -1          7.0
2      -1          6.5
3       0          7.5
4       0          7.0

## Key Insight:

- DataFrame behaves as BOTH dictionary (columns) and matrix (2D array)  
- Column access returns Series  
- `loc` = label-based, `iloc` = position-based  
- Boolean masks operate row-wise  
- Column-first access is fundamental structural convention

##1.4 Operating on Data in Pandas

Pandas builds on NumPy’s element-wise computation model and fully supports universal functions (ufuncs) for fast numerical operations.

For single-input operations (such as negation or mathematical functions), Pandas preserves index and column labels in the output, ensuring that structure is maintained alongside computation.

For binary operations (such as addition or multiplication), Pandas automatically aligns data by index before performing the operation. This means values are matched based on labels rather than position, which reduces errors when combining datasets from different sources.

This alignment behavior makes data integration more robust, especially when working with heterogeneous or partially overlapping datasets.

Pandas also supports operations between Series and DataFrame objects, extending these element-wise and alignment-based behaviors to both one-dimensional and two-dimensional structures.

##1.4.1 Ufuncs: Index Preservation

Pandas is fully compatible with NumPy’s universal functions (ufuncs). This means any ufunc applied to a Series or DataFrame produces a Pandas object with the original index and structure preserved.

When applied to a Series, the operation is performed element-wise while retaining the index labels. When applied to a DataFrame, the operation is applied element-wise across the entire table, preserving both row and column labels.

Even more complex transformations, such as trigonometric functions or scaling operations, behave in the same way. The output remains aligned with the original structure, ensuring interpretability of results without losing contextual labels.

SERIES + UFUNC (INDEX PRESERVATION)

In [246]:
sepal_length = pd.Series(
    df["sepal length (cm)"].values,
    index=df.index
)

print("Original Series (first 5):\n", sepal_length.head())

# Apply NumPy ufunc
log_series = np.log(sepal_length)

print("\nAfter np.log (index preserved):\n", log_series.head())

Original Series (first 5):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
dtype: float64

After np.log (index preserved):
 0    1.629241
1    1.589235
2    1.547563
3    1.526056
4    1.609438
dtype: float64

MULTIPLE UFUNCS ON SERIES

In [247]:
scaled_series = np.sqrt(sepal_length) + np.sin(sepal_length)

print("\nComposite ufunc result:\n", scaled_series.head())

Composite ufunc result:
 0    1.332503
1    1.231142
2    1.168025
3    1.151070
4    1.277144
dtype: float64

 DATAFRAME-WIDE UFUNC APPLICATION

In [248]:
df_numeric = df.iloc[:, :4]

log_df = np.log(df_numeric)

print("\nDataFrame after np.log (structure preserved):\n", log_df.head())

DataFrame after np.log (structure preserved):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           1.629241          1.252763           0.336472         -1.609438
1           1.589235          1.098612           0.336472         -1.609438
2           1.547563          1.163151           0.262364         -1.609438
3           1.526056          1.131402           0.405465         -1.609438
4           1.609438          1.280934           0.336472         -1.609438

TRIGONOMETRIC UFUNCS ON DATAFRAME

In [249]:
sin_df = np.sin(df_numeric)

print("\nnp.sin applied to DataFrame:\n", sin_df.head())

np.sin applied to DataFrame:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.925815         -0.350783           0.985450          0.198669
1          -0.982453          0.141120           0.985450          0.198669
2          -0.999923         -0.058374           0.963558          0.198669
3          -0.993691          0.041581           0.997495          0.198669
4          -0.958924         -0.442520           0.985450          0.198669

SCALING TRANSFORMATION (scalar broadcasting + ufunc)

In [250]:
scaled_df = df_numeric * 10

print("\nScaled DataFrame (x10):\n", scaled_df.head())

Scaled DataFrame (x10):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0               51.0              35.0               14.0               2.0
1               49.0              30.0               14.0               2.0
2               47.0              32.0               13.0               2.0
3               46.0              31.0               15.0               2.0
4               50.0              36.0               14.0               2.0

 STRUCTURAL PRESERVATION CHECK

In [251]:
print("\nIndex preserved in Series:", log_series.index.equals(sepal_length.index))
print("Columns preserved in DataFrame:", log_df.columns.equals(df_numeric.columns))

Index preserved in Series: True
Columns preserved in DataFrame: True

## Key Insight:

- NumPy ufuncs operate element-wise on Pandas objects  
- Index and column labels are preserved automatically  
- Output remains structurally aligned with input  
- Enables vectorized computation without losing data context

##1.4.2 UFuncs: Index Alignment

When performing binary operations between two Series or DataFrames, Pandas automatically aligns data using index labels before computing results. This makes operations robust when datasets are incomplete or partially overlapping.

---

### Index alignment in Series

When two Series share only some common labels, Pandas matches values by index. Entries without a match produce missing values (NaN). The result contains the union of both index sets.

If needed, missing values can be handled explicitly using methods that allow a fill value instead of default NaN behavior.

---

### Index alignment in DataFrame

The same alignment logic extends to two-dimensional DataFrames. Both row and column labels are matched before performing operations.

If column or row labels differ between DataFrames, Pandas aligns them automatically and fills missing positions with NaN.

To control missing data behavior, operations can include a fill value (such as a scalar or computed statistic), which is used wherever alignment fails.

---

### Summary of behavior

- Alignment is label-based, not position-based  
- Missing matches result in NaN by default  
- `fill_value` can be used to replace missing entries  
- Both Series and DataFrame follow the same alignment rules  

This design ensures safe and consistent arithmetic across heterogeneous datasets.

 SERIES INDEX ALIGNMENT (PARTIAL OVERLAP)

In [252]:
s1 = pd.Series(df["sepal length (cm)"].values, index=df.index)
s2 = pd.Series(df["sepal width (cm)"].values, index=df.index)

In [253]:
# Create partial misalignment by subsetting indices
s1_partial = s1.iloc[:100]
s2_partial = s2.iloc[50:150]

print("Series 1 (partial):\n", s1_partial.head())
print("\nSeries 2 (partial):\n", s2_partial.head())

Series 1 (partial):
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
dtype: float64

Series 2 (partial):
 50    3.2
51    3.2
52    3.1
53    2.3
54    2.8
dtype: float64

In [254]:
# Alignment happens by index labels
aligned_sum = s1_partial + s2_partial

print("\nAligned Series Sum (NaN appears where no match exists):\n", aligned_sum.head(10))

Aligned Series Sum (NaN appears where no match exists):
 0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
dtype: float64

HANDLING MISSING VALUES WITH fill_value

In [255]:
aligned_sum_fill = s1_partial.add(s2_partial, fill_value=0)

print("\nAligned Series with fill_value=0:\n", aligned_sum_fill.head(10))

Aligned Series with fill_value=0:
 0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
5    5.4
6    4.6
7    5.0
8    4.4
9    4.9
dtype: float64

DATAFRAME INDEX ALIGNMENT (ROWS + COLUMNS)

In [256]:
df1 = df.iloc[:100, :3]  # subset columns
df2 = df.iloc[50:150, 1:4]  # shifted rows + different columns

print("\nDataFrame 1 shape:", df1.shape)
print("DataFrame 2 shape:", df2.shape)

df_sum = df1 + df2

print("\nDataFrame aligned addition (NaN where mismatch occurs):\n", df_sum.head())

DataFrame 1 shape: (100, 3)
DataFrame 2 shape: (100, 3)

DataFrame aligned addition (NaN where mismatch occurs):
    petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
0                NaN               NaN                NaN               NaN
1                NaN               NaN                NaN               NaN
2                NaN               NaN                NaN               NaN
3                NaN               NaN                NaN               NaN
4                NaN               NaN                NaN               NaN

DATAFRAME ALIGNMENT WITH fill_value (using add)

In [257]:
df_sum_fill = df1.add(df2, fill_value=0)

print("\nDataFrame with fill_value=0:\n", df_sum_fill.head())

DataFrame with fill_value=0:
    petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
0                1.4               NaN                5.1               3.5
1                1.4               NaN                4.9               3.0
2                1.3               NaN                4.7               3.2
3                1.5               NaN                4.6               3.1
4                1.4               NaN                5.0               3.6

- Pandas aligns data by LABELS, not positions  
- Series: union of indices with NaN for mismatches  
- DataFrame: alignment across both rows and columns  
- `fill_value` allows controlled replacement of missing matches  
- Ensures safe arithmetic on heterogeneous or incomplete datasets

##1.4.3 Ufuncs: Operations Between DataFrame and Series

When performing operations between a DataFrame and a Series, Pandas applies broadcasting rules similar to NumPy, while also preserving label alignment.

By default, operations are applied row-wise, meaning each row of the DataFrame is aligned with the Series and operated on element by element.

If column-wise behavior is desired, Pandas allows explicit control using axis parameters, enabling operations along columns instead of rows.

Crucially, Pandas aligns indices during these operations. This means that if a Series has only a subset of columns or rows from a DataFrame, only matching labels are operated on, while non-matching entries produce missing values (NaN).

This combination of broadcasting and label alignment ensures that computations remain both flexible and context-aware, reducing errors when working with partially overlapping datasets.

CREATE A SERIES (used for broadcasting)

In [258]:
feature_means = df.iloc[:, :4].mean()

print("\nFeature means (Series):\n", feature_means)

Feature means (Series):
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

ROW-WISE BROADCASTING (DEFAULT BEHAVIOR)

In [259]:
row_centered = df.iloc[:, :4] - feature_means

print("\nRow-wise broadcasting (first 5 rows):\n", row_centered.head())

Row-wise broadcasting (first 5 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          -0.743333          0.442667             -2.358         -0.999333
1          -0.943333         -0.057333             -2.358         -0.999333
2          -1.143333          0.142667             -2.458         -0.999333
3          -1.243333          0.042667             -2.258         -0.999333
4          -0.843333          0.542667             -2.358         -0.999333

 COLUMN-WISE BROADCASTING (EXPLICIT AXIS CONTROL)

In [260]:
# subtract row-wise means (axis=1)
row_means = df.iloc[:, :4].mean(axis=1)

column_centered = df.iloc[:, :4].sub(row_means, axis=0)

print("\nColumn-wise broadcasting (first 5 rows):\n", column_centered.head())

Column-wise broadcasting (first 5 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0              2.550             0.950             -1.150            -2.350
1              2.525             0.625             -0.975            -2.175
2              2.350             0.850             -1.050            -2.150
3              2.250             0.750             -0.850            -2.150
4              2.450             1.050             -1.150            -2.350

PARTIAL INDEX ALIGNMENT BETWEEN SERIES AND DATAFRAME

In [261]:
partial_series = pd.Series(
    feature_means.iloc[:2],  # only 2 matching columns
    index=feature_means.index[:2]
)

aligned_result = df.iloc[:, :4] + partial_series

print("\nPartial Series alignment (NaN expected):\n", aligned_result.head())

Partial Series alignment (NaN expected):
    petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
0                NaN               NaN          10.943333          6.557333
1                NaN               NaN          10.743333          6.057333
2                NaN               NaN          10.543333          6.257333
3                NaN               NaN          10.443333          6.157333
4                NaN               NaN          10.843333          6.657333

EXPLICIT AXIS CONTROL WITH SERIES

In [262]:
axis_result = df.iloc[:, :4].add(feature_means, axis=1)

print("\nAxis=1 controlled broadcasting (first 5 rows):\n", axis_result.head())

Axis=1 controlled broadcasting (first 5 rows):
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0          10.943333          6.557333              5.158          1.399333
1          10.743333          6.057333              5.158          1.399333
2          10.543333          6.257333              5.058          1.399333
3          10.443333          6.157333              5.258          1.399333
4          10.843333          6.657333              5.158          1.399333

- DataFrame-Series operations combine broadcasting + label alignment  
- Default behavior is row-wise alignment  
- `axis` parameter controls direction of operation  
- Missing labels result in NaN due to alignment rules  
- Enables safe vectorized computation on structured datasets

##1.5 Handling Missing Data

Real-world datasets are often incomplete, inconsistent, or heterogeneous, unlike clean examples typically used in tutorials. A common challenge is the presence of missing values, which may be represented in different ways depending on the data source.

In Pandas, missing data is generally represented using standardized markers such as NaN (Not a Number) or NA. This allows consistent handling across numerical and non-numerical datasets.

The section introduces how Pandas represents missing values internally and how it provides built-in tools to detect, manage, and operate on such values in a structured and controlled way.

##1.5.1 Trade-Offs in Missing Data Conventions

Missing data is handled mainly in two ways:

Masking approach: uses a separate Boolean mask to mark missing values. This preserves data but increases memory and computation cost.

Sentinel approach: uses special values like NaN or -9999 to represent missing data. This is simpler but can limit valid value ranges and requires special handling in computations.

Different systems choose different strategies depending on efficiency and data type support.

MASKING APPROACH (FIXED)

In [263]:
data = df.iloc[:, :4]  # isolate numeric features

# IMPORTANT: mask must match data shape exactly
mask = np.zeros(data.shape, dtype=bool)

# artificially mark missing values
mask[0:10, 0] = True
mask[20:30, 1] = True

masked_values = data.mask(mask)
print(masked_values.head(15))

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 NaN               3.5                1.4               0.2
1                 NaN               3.0                1.4               0.2
2                 NaN               3.2                1.3               0.2
3                 NaN               3.1                1.5               0.2
4                 NaN               3.6                1.4               0.2
5                 NaN               3.9                1.7               0.4
6                 NaN               3.4                1.4               0.3
7                 NaN               3.4                1.5               0.2
8                 NaN               2.9                1.4               0.2
9                 NaN               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

 SENTINEL APPROACH (NaN)

In [264]:
sentinel_df = data.copy()
sentinel_df.iloc[0:10, 0] = np.nan
sentinel_df.iloc[20:30, 1] = np.nan

print("\n---- SENTINEL (NaN) APPROACH ----")
print(sentinel_df.head(15))

---- SENTINEL (NaN) APPROACH ----
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 NaN               3.5                1.4               0.2
1                 NaN               3.0                1.4               0.2
2                 NaN               3.2                1.3               0.2
3                 NaN               3.1                1.5               0.2
4                 NaN               3.6                1.4               0.2
5                 NaN               3.9                1.7               0.4
6                 NaN               3.4                1.4               0.3
7                 NaN               3.4                1.5               0.2
8                 NaN               2.9                1.4               0.2
9                 NaN               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

ALT SENTINEL APPROACH (-9999)

In [265]:
sentinel_alt = data.copy()
sentinel_alt.iloc[0:10, 0] = -9999
sentinel_alt.iloc[20:30, 1] = -9999
print(sentinel_alt.head(15))

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             -9999.0               3.5                1.4               0.2
1             -9999.0               3.0                1.4               0.2
2             -9999.0               3.2                1.3               0.2
3             -9999.0               3.1                1.5               0.2
4             -9999.0               3.6                1.4               0.2
5             -9999.0               3.9                1.7               0.4
6             -9999.0               3.4                1.4               0.3
7             -9999.0               3.4                1.5               0.2
8             -9999.0               2.9                1.4               0.2
9             -9999.0               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

COMPUTATIONAL DIFFERENCE

In [266]:
print("\n---- COMPUTATION IMPACT ----")

print("Masked mean (NaN-safe):")
print(masked_values.mean())

print("\nSentinel mean (after cleaning required):")
print(sentinel_alt.replace(-9999, np.nan).mean())

---- COMPUTATION IMPACT ----
Masked mean (NaN-safe):
sepal length (cm)    5.913571
sepal width (cm)     3.033571
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Sentinel mean (after cleaning required):
sepal length (cm)    5.913571
sepal width (cm)     3.033571
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

- Mask must match EXACT shape of target DataFrame  
- Masking = explicit missing structure (safe but memory heavy)  
- Sentinel = embedded missing values (fast but error-prone)  
- NaN is the standard scientific computing convention in Pandas/NumPy

##1.5.2 Missing Data in Pandas

Pandas handles missing data through constraints imposed by NumPy, which lacks a universal NA system for non-floating types. Designing explicit NA representations for every NumPy dtype (as in R) would be computationally inefficient and overly complex due to NumPy’s wide range of integer and floating variants.

An alternative based on masked arrays was also rejected because it introduces extra memory overhead and computational complexity.

---

## Design Choice

Pandas instead uses sentinel values:

- `None` (Python object-based missing value)  
- `NaN` (IEEE floating-point missing value)  

---

## None: Pythonic missing data

- Works only in object arrays  
- Forces Python-level computation (slow)  
- Breaks numerical operations (e.g., aggregation errors)  

---

## NaN: Numerical missing data

- Stored in `float64` arrays  
- Fast and supported at NumPy level  
- Propagates through all arithmetic operations  
- Requires special functions (`np.nansum`, etc.) to ignore  

---

## Pandas behavior

- Treats `None` and `NaN` interchangeably  
- Automatically converts:
  - integers → floats when NA appears  
  - `None` → `NaN` in numeric contexts  
- Ensures consistency but may change data types during processing  

---

Pandas prioritizes performance and simplicity, using sentinel-based missing data handling with automatic type casting rather than complex per-type NA encodings.

In [267]:
# Keep only numeric feature block for clarity
data = df.iloc[:, :4].copy()

None (Python object missing data)

In [268]:
none_df = data.copy()

# inject Python None values (forces object dtype behavior)
none_df.iloc[0:5, 0] = None
none_df.iloc[10:15, 1] = None

print("\n---- NONE (object-based missing data) ----")
print(none_df.head(10))
print("\nDtype check (None causes object conversion):")
print(none_df.dtypes)

---- NONE (object-based missing data) ----
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                NaN               3.5                1.4               0.2
1                NaN               3.0                1.4               0.2
2                NaN               3.2                1.3               0.2
3                NaN               3.1                1.5               0.2
4                NaN               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

Dtype check (None causes object conversion):
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

NaN (IEEE floating-point missing data)

In [269]:
nan_df = data.copy()

nan_df.iloc[0:5, 0] = np.nan
nan_df.iloc[10:15, 1] = np.nan

print("\n---- NaN (floating-point missing data) ----")
print(nan_df.head(10))
print("\nDtype check (NaN preserves float dtype):")
print(nan_df.dtypes)

---- NaN (floating-point missing data) ----
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                NaN               3.5                1.4               0.2
1                NaN               3.0                1.4               0.2
2                NaN               3.2                1.3               0.2
3                NaN               3.1                1.5               0.2
4                NaN               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
8                4.4               2.9                1.4               0.2
9                4.9               3.1                1.5               0.1

Dtype check (NaN preserves float dtype):
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

COMPUTATIONAL BEHAVIOR COMPARISON

In [270]:
# None-based data → requires object handling, often slower or breaks numerics
print("None-based mean (may fail or degrade):")
try:
    print(none_df.mean(numeric_only=True))
except Exception as e:
    print("Error:", e)

# NaN-based data → NumPy-compatible missing handling
print("\nNaN-based mean (automatic propagation):")
print(nan_df.mean())

print("\nNaN-safe aggregation:")
print(np.nansum(nan_df.to_numpy()))

None-based mean (may fail or degrade):
sepal length (cm)    5.877241
sepal width (cm)     3.044828
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

NaN-based mean (automatic propagation):
sepal length (cm)    5.877241
sepal width (cm)     3.044828
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

NaN-safe aggregation:
2037.3

TYPE CONVERSION EFFECT (PANDAS BEHAVIOR)

In [271]:
mixed = data.copy()
mixed.iloc[0, 0] = None  # triggers upcasting
print(mixed.head())
print("\nDtypes after inserting None:")
print(mixed.dtypes)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                NaN               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Dtypes after inserting None:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

- Pandas uses sentinel-based missing data (None, NaN)  
- None forces object dtype → slower computation  
- NaN integrates with NumPy float64 → efficient processing  
- Missing values trigger automatic type promotion  
- Design prioritizes performance over full per-type NA system

##1.5.3 Operating on Null Values

Pandas treats `None` and `NaN` similarly and provides built-in tools to manage missing data:

- `isnull()` → identifies missing values (Boolean mask)  
- `notnull()` → identifies non-missing values  
- `dropna()` → removes missing data  
- `fillna()` → replaces or imputes missing values  

These functions enable efficient detection, filtering, and handling of null data.

## Detecting Null Values

Pandas provides:

- `isnull()` → returns Boolean mask of missing values  
- `notnull()` → returns Boolean mask of non-missing values  

These masks can be used for filtering data, e.g., selecting only non-null entries.

## Dropping Null Values

Use `dropna()` to remove NA values and `fillna()` to replace them.

### For Series:
- Simply removes null entries  

### For DataFrame:
- Drops entire rows or columns (not individual cells)  
- Default: drops rows with any null value (`how='any'`)  
- `axis=1`: drops columns with nulls  

### More control:
- `how='all'` → drop only rows/columns where all values are null  
- `thresh` → keep rows/columns with a minimum number of non-null values  

Overall: `dropna()` provides flexible control over removing missing data.

## Filling Null Values

`fillna()` replaces missing values instead of dropping them.

- Can use a constant value (e.g., 0) to fill all nulls  
- Supports forward-fill (`ffill`): fills using previous value  
- Supports backward-fill (`bfill`): fills using next value  
- For DataFrames, filling can be done along rows or columns using `axis`  
- If no prior (or next) value exists during fill, the null remains

 LOAD IRIS DATASET

In [272]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["target"] = iris.target

INTRODUCE MISSING VALUES (FOR DEMONSTRATION)

In [273]:
data = df.copy()

data.iloc[0:5, 0] = np.nan       # NaN in sepal length
data.iloc[10:15, 1] = None       # None → becomes NaN
data.iloc[20:25, 2] = np.nan
data.head(12)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,NaN,3.5,1.4,0.2,0
1,NaN,3.0,1.4,0.2,0
2,NaN,3.2,1.3,0.2,0
3,NaN,3.1,1.5,0.2,0
4,NaN,3.6,1.4,0.2,0
5,5.4,3.9,1.7,0.4,0
6,4.6,3.4,1.4,0.3,0
7,5.0,3.4,1.5,0.2,0
8,4.4,2.9,1.4,0.2,0
9,4.9,3.1,1.5,0.1,0
10,5.4,NaN,1.5,0.2,0
11,4.8,NaN,1.6,0.2,0

DETECTING NULL VALUES

In [274]:
 data.isnull().head(12)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,True,False,False,False,False
1,True,False,False,False,False
2,True,False,False,False,False
3,True,False,False,False,False
4,True,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False
10,False,True,False,False,False
11,False,True,False,False,False

In [275]:
data.notnull().head(12)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,False,True,True,True,True
1,False,True,True,True,True
2,False,True,True,True,True
3,False,True,True,True,True
4,False,True,True,True,True
5,True,True,True,True,True
6,True,True,True,True,True
7,True,True,True,True,True
8,True,True,True,True,True
9,True,True,True,True,True
10,True,False,True,True,True
11,True,False,True,True,True

DROPPING NULL VALUES

In [276]:
# --- Series example ---
series_example = data["sepal length (cm)"]

series_dropped = series_example.dropna()
series_dropped

5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 145, dtype: float64

In [277]:
# --- DataFrame examples ---

# Drop rows with ANY nulls (default)
df_drop_any = data.dropna()

# Drop rows only if ALL values are null
df_drop_all = data.dropna(how='all')

# Drop columns containing any null values
df_drop_cols = data.dropna(axis=1)

# Keep rows with at least 4 non-null values
df_thresh = data.dropna(thresh=4)

print("\n---- DATAFRAME dropna() ----")
print("Drop rows (any nulls):", df_drop_any.shape)
print("Drop rows (all nulls):", df_drop_all.shape)
print("Drop columns with nulls:", df_drop_cols.columns.tolist())
print("Threshold (≥4 non-null values):", df_thresh.shape)

---- DATAFRAME dropna() ----
Drop rows (any nulls): (135, 5)
Drop rows (all nulls): (150, 5)
Drop columns with nulls: ['petal width (cm)', 'target']
Threshold (≥4 non-null values): (150, 5)

 FILLING NULL VALUES

In [278]:
# Constant fill
filled_constant = data.fillna(0)
filled_constant

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,0.0,3.5,1.4,0.2,0
1,0.0,3.0,1.4,0.2,0
2,0.0,3.2,1.3,0.2,0
3,0.0,3.1,1.5,0.2,0
4,0.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [279]:
# Forward fill (propagate previous value)
filled_ffill = data.fillna(method='ffill')
filled_ffill

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,NaN,3.5,1.4,0.2,0
1,NaN,3.0,1.4,0.2,0
2,NaN,3.2,1.3,0.2,0
3,NaN,3.1,1.5,0.2,0
4,NaN,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [280]:
# Backward fill (propagate next value)
filled_bfill = data.fillna(method='bfill')
filled_bfill

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.4,3.5,1.4,0.2,0
1,5.4,3.0,1.4,0.2,0
2,5.4,3.2,1.3,0.2,0
3,5.4,3.1,1.5,0.2,0
4,5.4,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

AXIS-BASED FILLING (DATAFRAME CONTROL)

In [281]:
# Fill column-wise (default behavior)
filled_axis0 = data.fillna(method='ffill', axis=0)
filled_axis0

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,NaN,3.5,1.4,0.2,0
1,NaN,3.0,1.4,0.2,0
2,NaN,3.2,1.3,0.2,0
3,NaN,3.1,1.5,0.2,0
4,NaN,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [282]:
# Fill row-wise
filled_axis1 = data.fillna(method='ffill', axis=1)
filled_axis1

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,NaN,3.5,1.4,0.2,0.0
1,NaN,3.0,1.4,0.2,0.0
2,NaN,3.2,1.3,0.2,0.0
3,NaN,3.1,1.5,0.2,0.0
4,NaN,3.6,1.4,0.2,0.0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2.0
146,6.3,2.5,5.0,1.9,2.0
147,6.5,3.0,5.2,2.0,2.0
148,6.2,3.4,5.4,2.3,2.0
149,5.9,3.0,5.1,1.8,2.0

## Key Insight

- Pandas treats `None` and `NaN` as missing values  
- `isnull()` / `notnull()` → detection via Boolean masks  
- `dropna()` → removes missing data with flexible rules  
- `fillna()` → replaces missing values (constant or propagation)  
- `axis` controls direction of filling in DataFrames  
- If no previous/next value exists, `NaN` remains