<a href="https://colab.research.google.com/github/sethkipsangmutuba/Data-Visualization/blob/main/Session_B3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Seth Kipsang
## Aggregation and Grouping  
- Planets Data  
- Simple Aggregation in Pandas  
- GroupBy: Split, Apply, Combine  
##Pivot Tables  
- Motivating Pivot Tables  
- Pivot Tables by Hand  
- Pivot Table Syntax  
- Example: Birthrate Data  
##Vectorized String Operations  
- Introducing Pandas String Operations  
- Tables of Pandas String Methods

#1 Aggregation and Grouping

##1.1 Planets Data

The Planets dataset comes from the Seaborn library and contains information about exoplanets discovered around other stars.

- Contains data on over 1,000 exoplanets discovered up to 2014  
- Each row represents a planet observation  
- Typical columns include:  
  - discovery method  
  - number of planets in system  
  - orbital period  
  - mass  
  - distance from Earth  
  - discovery year  
- Dataset shape: 1035 rows × 6 columns  

Purpose:
- Used for demonstrating data aggregation and grouping techniques in Pandas

LOAD PLANETS DATASET

In [942]:
import seaborn as sns
planets = sns.load_dataset("planets")
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

BASIC STRUCTURE CHECK

In [943]:
planets.shape

(1035, 6)

FIRST 5 ROWS

In [944]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

COLUMN NAMES

In [945]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

DATA INFO

In [946]:
planets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   object
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB

- Each row represents a confirmed exoplanet observation  
- Dataset includes discovery method, orbital properties, and system characteristics  
- Contains missing values, making it ideal for real-world Pandas analysis  
- Commonly used for grouping, aggregation, and time-based trend analysis

##1.2 Simple Aggregation in Pandas

Pandas aggregation works like NumPy: a Series returns a single summary value (sum, mean, etc.), while a DataFrame aggregates column-wise by default. Row-wise aggregation is possible using the `axis` argument.

The `describe()` method provides a quick summary of a dataset, including count, mean, standard deviation, min, max, and quartiles. For example, the Planets dataset shows exoplanet discoveries from 1989 to 2014, with a concentration after 2010 due to the Kepler mission.

---

## Common Pandas aggregation methods include:

- `count()`, `first()`, `last()`  
- `mean()`, `median()`  
- `min()`, `max()`  
- `std()`, `var()`, `mad()`  
- `sum()`, `prod()`  

---

For deeper analysis, `groupby` enables aggregation on subsets of data efficiently.

SERIES AGGREGATION (1D SUMMARY)

In [947]:
import numpy as np
import pandas as pd
import seaborn as sns

orbital_period = planets["orbital_period"]

print("\n--- SERIES AGGREGATION ---")
print("Count:", orbital_period.count())
print("Mean:", orbital_period.mean())
print("Median:", orbital_period.median())
print("Min:", orbital_period.min())
print("Max:", orbital_period.max())
print("Std:", orbital_period.std())
print("Sum:", orbital_period.sum())

--- SERIES AGGREGATION ---
Count: 992
Mean: 2002.9175960947582
Median: 39.9795
Min: 0.09070629
Max: 730000.0
Std: 26014.72830406252
Sum: 1986894.255326

DATAFRAME COLUMN-WISE AGGREGATION (DEFAULT AXIS=0)

DATAFRAME COLUMN-WISE MEAN

In [948]:
planets.mean(numeric_only=True)

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

DATAFRAME COLUMN-WISE SUMMARY STATS (DESCRIBE)

In [949]:
planets.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

 ROW-WISE AGGREGATION (axis=1)

In [950]:
numeric_cols = planets.select_dtypes(include=[np.number])

planets["row_mean"] = numeric_cols.mean(axis=1)
planets["row_sum"] = numeric_cols.sum(axis=1)

print("\n-- ROW-WISE AGGREGATION SAMPLE --")
print(planets[["row_mean", "row_sum"]].head())

-- ROW-WISE AGGREGATION SAMPLE --
   row_mean   row_sum
0  472.1600  2360.800
1  588.5868  2942.934
2  559.4880  2797.440
3  492.8100  2464.050
4  531.2380  2656.190

- Series aggregation collapses data into a single scalar summary  
- DataFrame aggregation is column-wise by default (axis=0)  
- axis=1 enables row-wise aggregation across features  
- describe() provides a compact statistical overview  
- Missing values are automatically ignored in most aggregations

##1.3 GroupBy: Split, Apply, Combine

Purpose: Conditional aggregation based on labels or index.  
Method: `groupby` operation in Pandas.  
Origin: Similar to SQL “GROUP BY”; concept popularized as “split-apply-combine” by Hadley Wickham.  

Idea:
- Split data into groups by key  
- Apply operations within each group  
- Combine results into final output

##1.3.1 Split, Apply, Combine

Example idea: Summation is a typical “apply” operation in split-apply-combine.

---

### Split step:
Data is divided into groups based on a key column or label.

---

### Apply step:
A function is applied within each group (commonly aggregation, transformation, or filtering).

---

### Combine step:
Results from each group are merged into a single output structure.

---

## Key insight:
This process can be done efficiently without explicitly creating separate subsets of data.

---

## GroupBy mechanism:
Pandas internally handles grouping in a single pass, updating aggregates like sum, mean, count, or min per group.

---

## Important concept:
`groupby` does not immediately compute results; it creates a lazy GroupBy object that waits for an operation.

---

## Outcome:
Once an aggregation (e.g., sum) is applied, grouped results are computed and returned as a summarized dataset.

LOAD DATA

In [951]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset("planets")

# clean minimal subset for stable grouping
planets = planets.dropna(subset=["method", "year", "orbital_period"])
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[992 rows x 6 columns]

SPLIT → APPLY → COMBINE (EXPLICIT DEMONSTRATION)

In [952]:
# SPLIT (group formation)
groups = planets.groupby("method")
groups

In [953]:
# APPLY (aggregation step)
sum_per_group = groups["orbital_period"].sum()
sum_per_group

method
Astrometry                       1.262360e+03
Eclipse Timing Variations        4.276480e+04
Imaging                          1.418973e+06
Microlensing                     2.207500e+04
Orbital Brightness Modulation    2.127920e+00
Pulsar Timing                    3.671511e+04
Pulsation Timing Variations      1.170000e+03
Radial Velocity                  4.553151e+05
Transit                          8.377523e+03
Transit Timing Variations        2.393505e+02
Name: orbital_period, dtype: float64

In [954]:
# COMBINE (final structured output)
result = sum_per_group.reset_index(name="total_orbital_period")
result

                          method  total_orbital_period
0                     Astrometry          1.262360e+03
1      Eclipse Timing Variations          4.276480e+04
2                        Imaging          1.418973e+06
3                   Microlensing          2.207500e+04
4  Orbital Brightness Modulation          2.127920e+00
5                  Pulsar Timing          3.671511e+04
6    Pulsation Timing Variations          1.170000e+03
7                Radial Velocity          4.553151e+05
8                        Transit          8.377523e+03
9      Transit Timing Variations          2.393505e+02

INTERNAL MECHANISM INTUITION (NO EXPLICIT SPLITTING)

In [955]:
manual_check = (
    planets
    .groupby("method")["orbital_period"]
    .mean()
)
manual_check

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

LAZY EVALUATION DEMONSTRATION

In [956]:
lazy_object = planets.groupby("method")
lazy_object

In [957]:
# nothing computed until an operation is invoked
computed_count = lazy_object.size()
computed_count

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           12
Microlensing                       7
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          3
dtype: int64

- Split: data is logically partitioned by key (not physically separated)  
- Apply: computation happens within each group  
- Combine: results are merged into a structured output  
- GroupBy is lazy: no computation until aggregation is triggered  
- Pandas performs grouping in optimized internal passes rather than manual loops

##1.3.2 The GroupBy Object

The GroupBy object is a flexible abstraction that behaves like a collection of grouped DataFrames, while deferring computation until an operation is applied.

Key idea: it enables efficient grouped analysis without manually splitting data.

---

## Core functionality

The most important GroupBy operations are:

- aggregation  
- filtering  
- transformation  
- apply  

These allow computation on subsets of data before recombining results.

---

## Column indexing

You can select specific columns within a GroupBy object. This narrows the focus to a Series-level grouping, but still delays computation until an operation (like median) is applied.

---

## Iteration over groups

GroupBy supports looping over groups, where each group is returned as a separate DataFrame or Series. This is useful for inspection or custom processing, though less efficient than built-in methods.

---

## Dispatch methods

Many standard DataFrame/Series methods automatically work on GroupBy objects. They are applied independently to each group, and results are recombined.

A common example is descriptive statistics per group, which helps reveal distributional differences across categories (e.g., discovery methods in the Planets dataset).

---

## Key insight

GroupBy applies operations per group automatically and efficiently, without requiring manual splitting. Any valid DataFrame or Series method can often be used, making it a powerful tool for structured data analysis.

 LOAD DATASET

In [958]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset("planets")
planets = planets.dropna(subset=["method", "orbital_period", "year"])

CREATE GROUPBY OBJECT (LAZY STRUCTURE)

In [959]:
grouped = planets.groupby("method")
grouped

COLUMN INDEXING (SERIES-LEVEL GROUPING)

In [960]:
orbital_group = grouped["orbital_period"]
orbital_group

In [961]:
orbital_group.median().head()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Name: orbital_period, dtype: float64

ITERATION OVER GROUPS (EXPLICIT INSPECTION)

In [962]:
print("\n--- SAMPLE GROUP ITERATION ---")
for name, group in grouped:
    print("\nMETHOD:", name)
    print(group.head())
    break  # keep output compact

--- SAMPLE GROUP ITERATION ---

METHOD: Astrometry
         method  number  orbital_period  mass  distance  year
113  Astrometry       1          246.36   NaN     20.77  2013
537  Astrometry       1         1016.00   NaN     14.98  2010

 AGGREGATION (CORE OPERATION)

In [963]:
agg_result = grouped["orbital_period"].agg(["count", "mean", "median"])
agg_result

                               count           mean        median
method
Astrometry                         2     631.180000    631.180000
Eclipse Timing Variations          9    4751.644444   4343.500000
Imaging                           12  118247.737500  27500.000000
Microlensing                       7    3153.571429   3300.000000
Orbital Brightness Modulation      3       0.709307      0.342887
Pulsar Timing                      5    7343.021201     66.541900
Pulsation Timing Variations        1    1170.000000   1170.000000
Radial Velocity                  553     823.354680    360.200000
Transit                          397      21.102073      5.714932
Transit Timing Variations          3      79.783500     57.011000

DISPATCH METHOD (describe applied per group)

In [964]:
desc = grouped["orbital_period"].describe()
desc

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,631.180000,544.217663,246.360000,438.770000,631.180000,823.590000,1016.000000
Eclipse Timing Variations,9.0,4751.644444,2499.130945,1916.250000,2900.000000,4343.500000,5767.000000,10220.000000
Imaging,12.0,118247.737500,213978.177277,4639.150000,8343.900000,27500.000000,94250.000000,730000.000000
Microlensing,7.0,3153.571429,1113.166333,1825.000000,2375.000000,3300.000000,3550.000000,5100.000000
Orbital Brightness Modulation,3.0,0.709307,0.725493,0.240104,0.291496,0.342887,0.943908,1.544929
Pulsar Timing,5.0,7343.021201,16313.265573,0.090706,25.262000,66.541900,98.211400,36525.000000
Pulsation Timing Variations,1.0,1170.000000,NaN,1170.000000,1170.000000,1170.000000,1170.000000,1170.000000
Radial Velocity,553.0,823.354680,1454.926210,0.736540,38.021000,360.200000,982.000000,17337.500000
Transit,397.0,21.102073,46.185893,0.355000,3.160630,5.714932,16.145700,331.600590
Transit Timing Variations,3.0,79.783500,71.599884,22.339500,39.675250,57.011000,108.505500,160.000000

FILTER EXAMPLE (GROUP-LEVEL CONDITION)

In [965]:
filtered = grouped.filter(lambda x: len(x) > 20)

print("\n--- FILTERED GROUPS (size > 20) ---")
print(filtered["method"].value_counts().head())

--- FILTERED GROUPS (size > 20) ---
method
Radial Velocity    553
Transit            397
Name: count, dtype: int64

TRANSFORMATION (SHAPE-PRESERVING OPERATION)

In [966]:
planets["centered_period"] = grouped["orbital_period"].transform(
    lambda x: x - x.mean()
)

print("\n--- TRANSFORM EXAMPLE ---")
print(planets[["method", "orbital_period", "centered_period"]].head())

--- TRANSFORM EXAMPLE ---
            method  orbital_period  centered_period
0  Radial Velocity         269.300       -554.05468
1  Radial Velocity         874.774         51.41932
2  Radial Velocity         763.000        -60.35468
3  Radial Velocity         326.030       -497.32468
4  Radial Velocity         516.220       -307.13468

- GroupBy behaves like a deferred collection of grouped DataFrames
- No computation occurs until an operation is invoked
- Supports aggregation, filtering, transformation, and apply
- Column indexing narrows focus while retaining lazy evaluation
- Many Pandas methods automatically dispatch per group
- Enables scalable grouped analysis without manual splitting

##1.3.3. Aggregate, Filter, Transform, Apply (Reduced Notes)

GroupBy objects support four key operations before combining results: `aggregate()`, `filter()`, `transform()`, and `apply()`. These extend basic aggregation into more flexible group-level computations.

---

## Aggregation

Aggregation summarizes each group into reduced statistics (e.g., min, median, max). It can:

- apply multiple functions at once  
- target specific columns using mappings  

This produces compact summaries of each group.

---

## Filtering

Filtering removes entire groups based on a condition.

- A function is applied to each group  
- It returns True/False  
- Only groups passing the condition are kept  

Example idea: keep groups whose variability exceeds a threshold.

---

## Transformation

Transformation keeps the same shape as the original data.

- Operates group-wise  
- Returns transformed values aligned with original structure  
- Common use: centering or standardizing data within groups (e.g., subtracting group mean)  

Unlike aggregation, it does not reduce data size.

---

## Apply

Apply is the most flexible operation.

- Takes each group as a DataFrame  
- Returns either:
  - a DataFrame/Series, or  
  - a scalar value  
- Allows fully custom logic per group  

Example use: normalize one column using another group-wise statistic.

---

## Key takeaway

- Aggregate → reduces data  
- Filter → removes groups  
- Transform → keeps shape, modifies values  
- Apply → fully flexible custom computation  

Together, these make GroupBy a powerful framework for structured, group-level data analysis.

 LOAD DATASET

In [967]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset("planets")
planets = planets.dropna(subset=["method", "orbital_period", "year"]).copy()

grouped = planets.groupby("method")
grouped

AGGREGATION (REDUCTION PER GROUP)

AGGREGATION (SINGLE COLUMN)

In [968]:
agg_result = grouped["orbital_period"].agg(["min", "median", "max"])
agg_result

                                       min        median            max
method
Astrometry                      246.360000    631.180000    1016.000000
Eclipse Timing Variations      1916.250000   4343.500000   10220.000000
Imaging                        4639.150000  27500.000000  730000.000000
Microlensing                   1825.000000   3300.000000    5100.000000
Orbital Brightness Modulation     0.240104      0.342887       1.544929
Pulsar Timing                     0.090706     66.541900   36525.000000
Pulsation Timing Variations    1170.000000   1170.000000    1170.000000
Radial Velocity                   0.736540    360.200000   17337.500000
Transit                           0.355000      5.714932     331.600590
Transit Timing Variations        22.339500     57.011000     160.000000

AGGREGATION (MULTI COLUMN)

In [969]:
agg_multi = grouped.agg({
    "orbital_period": ["mean", "std"],
    "year": "count"
})
agg_multi

                              orbital_period                 year
                                        mean            std count
method
Astrometry                        631.180000     544.217663     2
Eclipse Timing Variations        4751.644444    2499.130945     9
Imaging                        118247.737500  213978.177277    12
Microlensing                     3153.571429    1113.166333     7
Orbital Brightness Modulation       0.709307       0.725493     3
Pulsar Timing                    7343.021201   16313.265573     5
Pulsation Timing Variations      1170.000000            NaN     1
Radial Velocity                   823.354680    1454.926210   553
Transit                            21.102073      46.185893   397
Transit Timing Variations          79.783500      71.599884     3

FILTERING (GROUP SELECTION LOGIC)

In [970]:
filtered = grouped.filter(lambda g: g["orbital_period"].std() > 1000)

print("\n--- FILTERED GROUPS (STD > 1000)---")
filtered["method"].value_counts()

--- FILTERED GROUPS (STD > 1000)---

method
Radial Velocity              553
Imaging                       12
Eclipse Timing Variations      9
Microlensing                   7
Pulsar Timing                  5
Name: count, dtype: int64

TRANSFORMATION (SHAPE PRESERVING)

In [971]:
planets["centered_period"] = grouped["orbital_period"].transform(
    lambda x: x - x.mean()
)

planets["standardized_period"] = grouped["orbital_period"].transform(
    lambda x: (x - x.mean()) / x.std()
)

print("\n--- TRANSFORMATION SAMPLE ---")
planets[["method", "orbital_period", "centered_period", "standardized_period"]]

--- TRANSFORMATION SAMPLE ---

               method  orbital_period  centered_period  standardized_period
0     Radial Velocity      269.300000      -554.054680            -0.380813
1     Radial Velocity      874.774000        51.419320             0.035342
2     Radial Velocity      763.000000       -60.354680            -0.041483
3     Radial Velocity      326.030000      -497.324680            -0.341821
4     Radial Velocity      516.220000      -307.134680            -0.211100
...               ...             ...              ...                  ...
1030          Transit        3.941507       -17.160566            -0.371554
1031          Transit        2.615864       -18.486209            -0.400257
1032          Transit        3.191524       -17.910549            -0.387793
1033          Transit        4.125083       -16.976990            -0.367580
1034          Transit        4.187757       -16.914316            -0.366223

[992 rows x 4 columns]

 APPLY (FULL FLEXIBILITY PER GROUP)

In [972]:
def custom_scaling(group):
    x = group["orbital_period"]
    return (x - x.min()) / (x.max() - x.min())

applied = grouped.apply(custom_scaling)
applied

/tmp/ipykernel_13159/1535561042.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  applied = grouped.apply(custom_scaling)

method
Astrometry                 113     0.000000
                           537     1.000000
Eclipse Timing Variations  32      1.000000
                           37      0.463736
                           38      0.169171
                                     ...
Transit                    1033    0.011382
                           1034    0.011571
Transit Timing Variations  680     1.000000
                           736     0.251862
                           813     0.000000
Name: orbital_period, Length: 992, dtype: float64

- Aggregate → compresses each group into summary statistics
- Filter → removes entire groups based on logical condition
- Transform → preserves original shape while modifying values
- Apply → fully flexible, allows arbitrary group-level computation
- Together → constitute the full GroupBy analytical framework

##1.3.4 Specifying the Split Key (Reduced Notes)

GroupBy does not have to rely on a single column. The grouping key can be defined in multiple flexible ways.

---

## List / array / Series as keys

You can pass an external sequence of labels (same length as the DataFrame) to define groups.  
This allows grouping independent of existing columns.

---

## Column-based grouping (standard approach)

Grouping by a column is essentially equivalent to supplying that column as a key array.  
This is the most common and direct method.

---

## Dictionary or Series mapping

A mapping can assign each index value to a group label.

- Useful when categories are not directly stored in the data  
- Example idea: mapping categories like “A → vowel group”, “B/C → consonant group”  

This enables semantic grouping beyond raw data structure.

---

## Python function as key

A function can be applied to index values to determine grouping.

- Flexible and dynamic  
- Example: converting labels to lowercase or applying custom logic  

---

## Multiple keys (multi-level grouping)

You can combine multiple grouping strategies at once.

- Allows hierarchical grouping  
- Produces multi-index style grouped results  
- Useful for more granular aggregation patterns  

---

## Key takeaway

GroupBy supports data-driven, mapping-driven, function-driven, and multi-key grouping, making it highly adaptable for complex analytical structures beyond simple column-based splits.

LOAD DATASET

In [973]:
import numpy as np
import pandas as pd
import seaborn as sns

planets = sns.load_dataset("planets").dropna(subset=["method", "orbital_period", "year"]).copy()

 LIST / ARRAY / SERIES AS KEYS (EXTERNAL GROUPING)

In [974]:
external_keys = np.where(planets["orbital_period"] > 1000, "long_period", "short_period")

group_external = planets.groupby(external_keys)["orbital_period"].mean()
group_external

long_period     11294.287527
short_period      149.137622
Name: orbital_period, dtype: float64

COLUMN-BASED GROUPING (STANDARD)

In [975]:
group_method = planets.groupby("method")["orbital_period"].mean()
group_method

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

DICTIONARY / SERIES MAPPING

In [976]:
method_map = {
    "Radial Velocity": "RV",
    "Transit": "Transit-Based",
    "Imaging": "Direct Imaging",
    "Microlensing": "Gravitational",
    "Eclipse Timing Variations": "Timing"
}

mapped_groups = planets["method"].map(method_map)
mapped_groups

0                  RV
1                  RV
2                  RV
3                  RV
4                  RV
            ...
1030    Transit-Based
1031    Transit-Based
1032    Transit-Based
1033    Transit-Based
1034    Transit-Based
Name: method, Length: 992, dtype: object

In [977]:
group_mapped = planets.groupby(mapped_groups)["orbital_period"].median()
group_mapped

method
Direct Imaging    27500.000000
Gravitational      3300.000000
RV                  360.200000
Timing             4343.500000
Transit-Based         5.714932
Name: orbital_period, dtype: float64

FUNCTION-BASED GROUPING

In [978]:
group_func = planets.groupby(lambda idx: len(str(idx)))["orbital_period"].mean()
group_func

1     695.316400
2    5799.519892
3    1758.333684
4       3.366273
Name: orbital_period, dtype: float64

MULTIPLE KEYS (HIERARCHICAL GROUPING)

In [979]:
planets["decade"] = (planets["year"] // 10) * 10

multi_group = planets.groupby(["method", "decade"])["orbital_period"].mean()
multi_group

method                         decade
Astrometry                     2010         631.180000
Eclipse Timing Variations      2000        6436.000000
                               2010        3909.466667
Imaging                        2000      150103.927778
                               2010       22679.166667
Microlensing                   2000        3465.000000
                               2010        2375.000000
Orbital Brightness Modulation  2010           0.709307
Pulsar Timing                  1990          63.338433
                               2000       36525.000000
                               2010           0.090706
Pulsation Timing Variations    2000        1170.000000
Radial Velocity                1980          83.888000
                               1990         389.843315
                               2000         852.273935
                               2010         841.688331
Transit                        2000           4.672745
                               2010          24.142724
Transit Timing Variations      2010          79.783500
Name: orbital_period, dtype: float64

- Grouping is not restricted to columns
- Keys can come from arrays, mappings, or functions
- Multi-key grouping creates hierarchical structure
- This enables flexible and semantically rich data partitioning

##2. Pivot Tables

Pivot tables extend the idea of GroupBy to two-dimensional summarization.

- They take column-based data and reorganize it into a matrix (rows × columns)  
- Provide multidimensional aggregation in a single view  

---

## Relationship to GroupBy

- Both follow split–apply–combine logic  
- GroupBy → operates along a single dimension  
- Pivot tables → operate across a two-dimensional grid  

---

## Key idea

Pivot tables are essentially a multidimensional version of GroupBy, enabling more compact and intuitive summaries of relationships within data.

##2.1 Motivating Pivot Tables

Pivot tables provide a clearer way to explore multidimensional relationships in data, using structured summaries instead of long GroupBy pipelines.

---

## Dataset context

The Titanic dataset contains rich passenger-level data (e.g., sex, age, class, fare, survival), making it ideal for demonstrating grouped analysis.

---

##2.2 Pivot Tables by Hand (via GroupBy)

Basic insight: survival differs strongly by gender  
→ females had much higher survival rates than males  

Extending analysis:
- Grouping by sex + class reveals combined effects  
- Requires chaining operations (groupby → aggregate → unstack)  
- Works, but becomes harder to read  

---

##2.3 Pivot Table Syntax

Pivot tables simplify this process:

- Replace complex GroupBy pipelines with a single, readable operation  
- Automatically produce 2D summaries (rows × columns)  

Example structure:
- rows → one variable (e.g., sex)  
- columns → another variable (e.g., class)  
- values → aggregated metric (e.g., survival rate)  

Key insight: survival improves with both being female and higher class.

---

##2.4 Multilevel Pivot Tables

Pivot tables can include more dimensions:

- Add variables (e.g., age groups using binning)  
- Include additional column groupings (e.g., fare categories)  
- Results form hierarchical (multi-index) tables  

This enables 3D or 4D summaries within a structured grid.

---

##2.5 Additional Options

Pivot tables are flexible via parameters:

- `aggfunc` → controls aggregation type (mean, sum, etc.)  
- dictionary mapping → apply different functions to different columns  
- `margins=True` → adds totals (overall summaries across rows/columns)  
- `fill_value` / `dropna` → handle missing data  

---

## Key takeaway

Pivot tables provide a clean, readable, and scalable alternative to GroupBy for multidimensional analysis, especially when exploring interactions between multiple variables.

LOAD TITANIC DATASET

In [980]:
import numpy as np
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

 DROP MISSING VALUES (CRITICAL PREPROCESSING)

In [981]:
titanic_clean = titanic.dropna(subset=["sex", "class", "age", "fare", "survived"]).copy()
titanic_clean

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

GROUPBY (PIVOT BY HAND)

In [982]:
# survival by sex
survival_sex = titanic_clean.groupby("sex")["survived"].mean()
survival_sex

sex
female    0.754789
male      0.205298
Name: survived, dtype: float64

In [983]:
# survival by sex + class
survival_sex_class = (
    titanic_clean
    .groupby(["sex", "class"])["survived"]
    .mean()
    .unstack()
)
survival_sex_class

class      First    Second     Third
sex
female  0.964706  0.918919  0.460784
male    0.396040  0.151515  0.150198

PIVOT TABLE (SIMPLIFIED APPROACH)

In [984]:
pivot_basic = titanic_clean.pivot_table(
    values="survived",
    index="sex",
    columns="class",
    aggfunc="mean"
)

print("\n----- PIVOT TABLE (SEX × CLASS) ---")
pivot_basic

----- PIVOT TABLE (SEX × CLASS) ---

class      First    Second     Third
sex
female  0.964706  0.918919  0.460784
male    0.396040  0.151515  0.150198

MULTILEVEL PIVOT TABLE (ADDING AGE GROUPS)

In [985]:
titanic_clean["age_group"] = pd.cut(
    titanic_clean["age"],
    bins=[0, 18, 40, 80],
    labels=["child", "adult", "senior"]
)
titanic_clean["age_group"]

0      adult
1      adult
2      adult
3      adult
4      adult
       ...
885    adult
886    adult
887    adult
889    adult
890    adult
Name: age_group, Length: 714, dtype: category
Categories (3, object): ['child' < 'adult' < 'senior']

In [986]:
pivot_multi = titanic_clean.pivot_table(
    values="survived",
    index=["sex", "age_group"],
    columns="class",
    aggfunc="mean"
)
pivot_multi

class                First    Second     Third
sex    age_group
female child      0.909091  1.000000  0.511628
       adult      0.979167  0.914894  0.480000
       senior     0.961538  0.846154  0.111111
male   child      0.800000  0.600000  0.215686
       adult      0.478261  0.063492  0.146199
       senior     0.280000  0.095238  0.064516

ADDITIONAL DIMENSION (FARE GROUPS)

In [987]:
titanic_clean["fare_group"] = pd.qcut(
    titanic_clean["fare"],
    3,
    labels=["low", "mid", "high"]
)
titanic_clean["fare_group"]

0       low
1      high
2       low
3      high
4       low
       ...
885    high
886     mid
887    high
889    high
890     low
Name: fare_group, Length: 714, dtype: category
Categories (3, object): ['low' < 'mid' < 'high']

In [988]:
pivot_advanced = titanic_clean.pivot_table(
    values="survived",
    index=["sex", "age_group"],
    columns=["class", "fare_group"],
    aggfunc="mean"
)
pivot_advanced

class            First                        Second          Third            \
fare_group         low       mid      high       mid high       low       mid
sex    age_group
female child       NaN       NaN  0.909091  1.000000  1.0  0.692308  0.571429
       adult       NaN  1.000000  0.978723  0.897436  1.0  0.428571  0.611111
       senior      NaN  1.000000  0.956522  0.833333  1.0  0.500000  0.000000
male   child       NaN       NaN  0.800000  0.500000  0.8  0.150000  0.583333
       adult       0.0  1.000000  0.444444  0.076923  0.0  0.138889  0.095238
       senior      NaN  0.333333  0.263158  0.105263  0.0  0.071429  0.000000

class
fare_group            high
sex    age_group
female child      0.111111
       adult      0.250000
       senior     0.000000
male   child      0.052632
       adult      0.500000
       senior          NaN

MULTIPLE AGGREGATIONS

In [989]:
pivot_multi_agg = titanic_clean.pivot_table(
    values=["survived", "fare"],
    index="sex",
    columns="class",
    aggfunc={"survived": "mean", "fare": "median"}
)
pivot_multi_agg

           fare                   survived
class     First Second     Third     First    Second     Third
sex
female  83.1583   22.0  12.94585  0.964706  0.918919  0.460784
male    52.0000   13.0   7.92500  0.396040  0.151515  0.150198

 MARGINS (TOTALS)

In [990]:
pivot_margins = titanic_clean.pivot_table(
    values="survived",
    index="sex",
    columns="class",
    aggfunc="mean",
    margins=True
)
pivot_margins

class      First    Second     Third       All
sex
female  0.964706  0.918919  0.460784  0.754789
male    0.396040  0.151515  0.150198  0.205298
All     0.655914  0.479769  0.239437  0.406162

- Missing values removed before analysis ensures valid aggregation
- Pivot tables replace complex groupby pipelines with clear structure
- MultiIndex pivots enable higher-dimensional analysis
- Aggregation, margins, and binning enhance interpretability

##3. Vectorized String Operations

Pandas extends Python’s string handling by providing vectorized string operations for efficient, column-wise text processing.

---

## Key idea

- Designed for cleaning and manipulating real-world text data  
- Operate on entire Series (not element-by-element loops)  
- Faster and more expressive than standard Python string handling  

---

## Importance

- Essential for data cleaning (“munging”)  
- Handles messy, inconsistent textual datasets (e.g., names, labels, descriptions)  

---

## Application

- Used to process and clean complex datasets (e.g., unstructured recipe data)  
- Enables scalable transformation of text into analyzable formats  

---

## Key takeaway

Vectorized string operations are a core tool in Pandas for efficient text preprocessing, especially in messy real-world datasets.